document.addEventListener('DOMContentLoaded', () => {
  const previewContainer = document.getElementById('previewContainer');
  const animationPlayer = document.getElementById('animationPlayer');
  const playBtn = document.getElementById('playBtn');
  const speedSlider = document.getElementById('speedSlider');
  const speedLabel = document.getElementById('speedLabel');

  let playing = false, playInterval = null, currentFrame = 0, frameDelay = 1000; // Default delay of 1 second

  // Handle speed slider
  speedSlider.addEventListener('input', () => {
    frameDelay = parseInt(speedSlider.value);
    speedLabel.textContent = (frameDelay / 1000).toFixed(1) + 's/frame'; // Display seconds in label
    if (playing) restartPlayback(); // Restart playback if already playing
  });

  function addPreview() {
    const section = document.createElement('div');
    section.className = 'accordion-section';
    
    const header = document.createElement('div');
    header.className = 'accordion-header';
    const title = document.createElement('h4');
    title.textContent = `Preview ${previewContainer.children.length + 1}`;
    const toggle = document.createElement('span');
    toggle.textContent = '+';
    const minimizeBtn = document.createElement('button');
    minimizeBtn.textContent = '–';
    minimizeBtn.style.marginLeft = '10px';

    header.appendChild(title);
    header.appendChild(toggle);
    header.appendChild(minimizeBtn);

    const content = document.createElement('div');
    content.className = 'accordion-content';

    const controlsDiv = document.createElement('div');
    controlsDiv.className = 'controls';
    controlsDiv.innerHTML = `
      <div class="symbolsContainer"></div>
      <button class="addSymbolBtn">Add Symbol +</button>
      <div class="imagesContainer" style="margin-top:10px;"></div>
      <button class="addImageBtn">Add Image +</button>
      <div class="settings" style="margin-top:10px;">
        <label>Font:
          <select class="fontSelect">
            <option value="Arial" selected>Arial</option>
            <option value="Michroma">Michroma</option>
            <option value="Pacifico">Pacifico</option>
            <option value="Courier New">Courier New</option>
            <option value="Georgia">Georgia</option>
            <option value="Times New Roman">Times New Roman</option>
            <option value="Verdana">Verdana</option>
          </select>
        </label>
      </div>
      <div class="panel-grid" id="panelContainer"></div>
    `;

    const preview = document.createElement('div');
    preview.className = 'preview';

    // Create textarea for HTML editing
    const textarea = document.createElement('textarea');
    textarea.readOnly = false;
    textarea.placeholder = 'Edit HTML here...';

    content.appendChild(controlsDiv);
    content.appendChild(preview);
    content.appendChild(document.createElement('br'));
    content.appendChild(textarea);

    section.appendChild(header);
    section.appendChild(content);
    previewContainer.appendChild(section);

    const previewObj = {
      section, header, content, preview, textarea,
      controlsDiv,
      symbolsContainer: controlsDiv.querySelector('.symbolsContainer'),
      imagesContainer: controlsDiv.querySelector('.imagesContainer'),
      fontSelect: controlsDiv.querySelector('.fontSelect')
    };

    // Sync textarea with preview
    textarea.addEventListener('input', () => {
      preview.innerHTML = textarea.value;
    });

    // Minimize button functionality
    header.addEventListener('click', (e) => {
      if (e.target === minimizeBtn) return;
      const active = section.classList.contains('active');
      document.querySelectorAll('.accordion-section').forEach(sec => sec.classList.remove('active'));
      if (!active) section.classList.add('active');
    });

    minimizeBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      content.style.display = content.style.display === 'none' ? 'block' : 'none';
    });

    // Adding Symbols and Images
    controlsDiv.querySelector('.addSymbolBtn').addEventListener('click', () => addSymbol(previewObj));
    controlsDiv.querySelector('.addImageBtn').addEventListener('click', () => addImage(previewObj));
    previewObj.fontSelect.addEventListener('change', () => updatePreview(previewObj));

    updatePreview(previewObj);
  }

  document.getElementById('addPreviewBtn').addEventListener('click', addPreview);
  addPreview();

  // ---- SYMBOLS ----
  function addSymbol(previewObj) {
    const div = document.createElement('div');
    div.className = 'input-group';
    div.dataset.top = 50;
    div.dataset.left = 50;
    div.innerHTML = `
      <input type="text" maxlength="3" class="symbolInput" placeholder="Symbol"/>
      <select class="unicodeSelect">
        <option value="">-- Unicode --</option>
        <option value="★">★ Star</option>
        <option value="✿">✿ Flower</option>
        <option value="☯">☯ Yin Yang</option>
        <option value="♡">♡ Heart</option>
        <option value="☀">☀ Sun</option>
        <option value="⚡">⚡ Lightning</option>
        <option value="!">!</option>
        <option value="🩰">🩰</option>
        <option value="🚀">🚀</option>
        <option value="🂠">🂠</option>
        <option value="🀰">🀰</option>
        <option value="𝄀">𝄀</option>
        <option value="⠁">⠁</option>
        <option value="✀">✀</option>
        <option value="☀">☀</option>
        <option value="⅐">⅐</option>
        <option value="℀">℀</option>
        <option value="₠">₠</option>
        <option value="‐">‐</option>
<option value="‑">‑</option>
<option value="‒">‒</option>
<option value="–">–</option>
<option value="—">—</option>
<option value="―">―</option>
<option value="‖">‖</option>
<option value="‗">‗</option>
<option value="‘">‘</option>
<option value="’">’</option>
<option value="‚">‚</option>
<option value="‛">‛</option>
<option value="“">“</option>
<option value="”">”</option>
<option value="„">„</option>
<option value="‟">‟</option>
<option value="†">†</option>
<option value="‡">‡</option>
<option value="•">•</option>
<option value="‣">‣</option>
<option value="․">․</option>
<option value="‥">‥</option>
<option value="…">…</option>
<option value="‧">‧</option>
<option value=" "> </option>
<option value="‰">‰</option>
<option value="‱">‱</option>
<option value="′">′</option>
<option value="″">″</option>
<option value="‴">‴</option>
<option value="‸">‸</option>
<option value="‹">‹</option>
<option value="›">›</option>
<option value="※">※</option>
<option value="‼">‼</option>
<option value="‽">‽</option>
<option value="‾">‾</option>
<option value="‿">‿</option>
<option value="⁀">⁀</option>
<option value="⁁">⁁</option>
<option value="⁂">⁂</option>
<option value="⁃">⁃</option>
<option value="⁄">⁄</option>
<option value="⁅">⁅</option>
<option value="⁆">⁆</option>
<option value="⁇">⁇</option>
<option value="⁈">⁈</option>
<option value="⁉">⁉</option>
<option value="⁊">⁊</option>
<option value="⁋">⁋</option>
<option value="⁌">⁌</option>
<option value="⁍">⁍</option>
<option value="⁎">⁎</option>
<option value="⁏">⁏</option>
<option value="⁐">⁐</option>
<option value="⁑">⁑</option>
<option value="⁒">⁒</option>
<option value="⁓">⁓</option>
<option value="⁔">⁔</option>
<option value="⁕">⁕</option>
<option value="⁖">⁖</option>
<option value="⁗">⁗</option>
<option value="⁘">⁘</option>
<option value="⁙">⁙</option>
<option value="⁚">⁚</option>
<option value="⁛">⁛</option>
<option value="⁜">⁜</option>
<option value="⁝">⁝</option>
<option value="⁞">⁞</option>
<option value="₡">₡</option>
<option value="₢">₢</option>
<option value="₣">₣</option>
<option value="₤">₤</option>
<option value="₥">₥</option>
<option value="₦">₦</option>
<option value="₧">₧</option>
<option value="₨">₨</option>
<option value="₩">₩</option>
<option value="₪">₪</option>
<option value="₫">₫</option>
<option value="€">€</option>
<option value="₭">₭</option>
<option value="₮">₮</option>
<option value="₯">₯</option>
<option value="₰">₰</option>
<option value="₱">₱</option>
<option value="₲">₲</option>
<option value="₳">₳</option>
<option value="₴">₴</option>
<option value="₵">₵</option>
<option value="₶">₶</option>
<option value="₷">₷</option>
<option value="₸">₸</option>
<option value="₹">₹</option>
<option value="₺">₺</option>
<option value="₻">₻</option>
<option value="₼">₼</option>
<option value="₽">₽</option>
<option value="₾">₾</option>
<option value="₿">₿</option>
<option value="⃀">⃀</option>
<option value="⃁">⃁</option>
<option value="℁">℁</option>
<option value="ℂ">ℂ</option>
<option value="℃">℃</option>
<option value="℄">℄</option>
<option value="℅">℅</option>
<option value="℆">℆</option>
<option value="ℇ">ℇ</option>
<option value="℈">℈</option>
<option value="℉">℉</option>
<option value="ℊ">ℊ</option>
<option value="ℋ">ℋ</option>
<option value="ℌ">ℌ</option>
<option value="ℍ">ℍ</option>
<option value="ℎ">ℎ</option>
<option value="ℏ">ℏ</option>
<option value="ℐ">ℐ</option>
<option value="ℑ">ℑ</option>
<option value="ℒ">ℒ</option>
<option value="ℓ">ℓ</option>
<option value="℔">℔</option>
<option value="ℕ">ℕ</option>
<option value="№">№</option>
<option value="℗">℗</option>
<option value="℘">℘</option>
<option value="ℙ">ℙ</option>
<option value="ℚ">ℚ</option>
<option value="ℛ">ℛ</option>
<option value="ℜ">ℜ</option>
<option value="ℝ">ℝ</option>
<option value="℞">℞</option>
<option value="℟">℟</option>
<option value="℠">℠</option>
<option value="℡">℡</option>
<option value="™">™</option>
<option value="℣">℣</option>
<option value="ℤ">ℤ</option>
<option value="℥">℥</option>
<option value="Ω">Ω</option>
<option value="℧">℧</option>
<option value="ℨ">ℨ</option>
<option value="℩">℩</option>
<option value="K">K</option>
<option value="Å">Å</option>
<option value="ℬ">ℬ</option>
<option value="ℭ">ℭ</option>
<option value="℮">℮</option>
<option value="ℯ">ℯ</option>
<option value="ℰ">ℰ</option>
<option value="ℱ">ℱ</option>
<option value="Ⅎ">Ⅎ</option>
<option value="ℳ">ℳ</option>
<option value="ℴ">ℴ</option>
<option value="ℵ">ℵ</option>
<option value="ℶ">ℶ</option>
<option value="ℷ">ℷ</option>
<option value="ℸ">ℸ</option>
<option value="ℹ">ℹ</option>
<option value="℺">℺</option>
<option value="℻">℻</option>
<option value="ℼ">ℼ</option>
<option value="ℽ">ℽ</option>
<option value="ℾ">ℾ</option>
<option value="ℿ">ℿ</option>
<option value="⅀">⅀</option>
<option value="⅁">⅁</option>
<option value="⅂">⅂</option>
<option value="⅃">⅃</option>
<option value="⅄">⅄</option>
<option value="ⅅ">ⅅ</option>
<option value="ⅆ">ⅆ</option>
<option value="ⅇ">ⅇ</option>
<option value="ⅈ">ⅈ</option>
<option value="ⅉ">ⅉ</option>
<option value="⅊">⅊</option>
<option value="⅋">⅋</option>
<option value="⅌">⅌</option>
<option value="⅍">⅍</option>
<option value="ⅎ">ⅎ</option>
<option value="⅏">⅏</option>
<option value="⅑">⅑</option>
<option value="⅒">⅒</option>
<option value="⅓">⅓</option>
<option value="⅔">⅔</option>
<option value="⅕">⅕</option>
<option value="⅖">⅖</option>
<option value="⅗">⅗</option>
<option value="⅘">⅘</option>
<option value="⅙">⅙</option>
<option value="⅚">⅚</option>
<option value="⅛">⅛</option>
<option value="⅜">⅜</option>
<option value="⅝">⅝</option>
<option value="⅞">⅞</option>
<option value="⅟">⅟</option>
<option value="Ⅰ">Ⅰ</option>
<option value="Ⅱ">Ⅱ</option>
<option value="Ⅲ">Ⅲ</option>
<option value="Ⅳ">Ⅳ</option>
<option value="Ⅴ">Ⅴ</option>
<option value="Ⅵ">Ⅵ</option>
<option value="Ⅶ">Ⅶ</option>
<option value="Ⅷ">Ⅷ</option>
<option value="Ⅸ">Ⅸ</option>
<option value="Ⅹ">Ⅹ</option>
<option value="Ⅺ">Ⅺ</option>
<option value="Ⅻ">Ⅻ</option>
<option value="Ⅼ">Ⅼ</option>
<option value="Ⅽ">Ⅽ</option>
<option value="Ⅾ">Ⅾ</option>
<option value="Ⅿ">Ⅿ</option>
<option value="ⅰ">ⅰ</option>
<option value="ⅱ">ⅱ</option>
<option value="ⅲ">ⅲ</option>
<option value="ⅳ">ⅳ</option>
<option value="ⅴ">ⅴ</option>
<option value="ⅵ">ⅵ</option>
<option value="ⅶ">ⅶ</option>
<option value="ⅷ">ⅷ</option>
<option value="ⅸ">ⅸ</option>
<option value="ⅹ">ⅹ</option>
<option value="ⅺ">ⅺ</option>
<option value="ⅻ">ⅻ</option>
<option value="ⅼ">ⅼ</option>
<option value="ⅽ">ⅽ</option>
<option value="ⅾ">ⅾ</option>
<option value="ⅿ">ⅿ</option>
<option value="ↀ">ↀ</option>
<option value="ↁ">ↁ</option>
<option value="ↂ">ↂ</option>
<option value="Ↄ">Ↄ</option>
<option value="ↄ">ↄ</option>
<option value="ↅ">ↅ</option>
<option value="ↆ">ↆ</option>
<option value="ↇ">ↇ</option>
<option value="ↈ">ↈ</option>
<option value="↉">↉</option>
<option value="↊">↊</option>
<option value="↋">↋</option>
<option value="☁">☁</option>
<option value="☂">☂</option>
<option value="☃">☃</option>
<option value="☄">☄</option>
<option value="★">★</option>
<option value="☆">☆</option>
<option value="☇">☇</option>
<option value="☈">☈</option>
<option value="☉">☉</option>
<option value="☊">☊</option>
<option value="☋">☋</option>
<option value="☌">☌</option>
<option value="☍">☍</option>
<option value="☎">☎</option>
<option value="☏">☏</option>
<option value="☐">☐</option>
<option value="☑">☑</option>
<option value="☒">☒</option>
<option value="☓">☓</option>
<option value="☔">☔</option>
<option value="☕">☕</option>
<option value="☖">☖</option>
<option value="☗">☗</option>
<option value="☘">☘</option>
<option value="☙">☙</option>
<option value="☚">☚</option>
<option value="☛">☛</option>
<option value="☜">☜</option>
<option value="☝">☝</option>
<option value="☞">☞</option>
<option value="☟">☟</option>
<option value="☠">☠</option>
<option value="☡">☡</option>
<option value="☢">☢</option>
<option value="☣">☣</option>
<option value="☤">☤</option>
<option value="☥">☥</option>
<option value="☦">☦</option>
<option value="☧">☧</option>
<option value="☨">☨</option>
<option value="☩">☩</option>
<option value="☪">☪</option>
<option value="☫">☫</option>
<option value="☬">☬</option>
<option value="☭">☭</option>
<option value="☮">☮</option>
<option value="☯">☯</option>
<option value="☰">☰</option>
<option value="☱">☱</option>
<option value="☲">☲</option>
<option value="☳">☳</option>
<option value="☴">☴</option>
<option value="☵">☵</option>
<option value="☶">☶</option>
<option value="☷">☷</option>
<option value="☸">☸</option>
<option value="☹">☹</option>
<option value="☺">☺</option>
<option value="☻">☻</option>
<option value="☼">☼</option>
<option value="☽">☽</option>
<option value="☾">☾</option>
<option value="☿">☿</option>
<option value="♀">♀</option>
<option value="♁">♁</option>
<option value="♂">♂</option>
<option value="♃">♃</option>
<option value="♄">♄</option>
<option value="♅">♅</option>
<option value="♆">♆</option>
<option value="♇">♇</option>
<option value="♈">♈</option>
<option value="♉">♉</option>
<option value="♊">♊</option>
<option value="♋">♋</option>
<option value="♌">♌</option>
<option value="♍">♍</option>
<option value="♎">♎</option>
<option value="♏">♏</option>
<option value="♐">♐</option>
<option value="♑">♑</option>
<option value="♒">♒</option>
<option value="♓">♓</option>
<option value="♔">♔</option>
<option value="♕">♕</option>
<option value="♖">♖</option>
<option value="♗">♗</option>
<option value="♘">♘</option>
<option value="♙">♙</option>
<option value="♚">♚</option>
<option value="♛">♛</option>
<option value="♜">♜</option>
<option value="♝">♝</option>
<option value="♞">♞</option>
<option value="♟">♟</option>
<option value="♠">♠</option>
<option value="♡">♡</option>
<option value="♢">♢</option>
<option value="♣">♣</option>
<option value="♤">♤</option>
<option value="♥">♥</option>
<option value="♦">♦</option>
<option value="♧">♧</option>
<option value="♨">♨</option>
<option value="♩">♩</option>
<option value="♪">♪</option>
<option value="♫">♫</option>
<option value="♬">♬</option>
<option value="♭">♭</option>
<option value="♮">♮</option>
<option value="♯">♯</option>
<option value="♰">♰</option>
<option value="♱">♱</option>
<option value="♲">♲</option>
<option value="♳">♳</option>
<option value="♴">♴</option>
<option value="♵">♵</option>
<option value="♶">♶</option>
<option value="♷">♷</option>
<option value="♸">♸</option>
<option value="♹">♹</option>
<option value="♺">♺</option>
<option value="♻">♻</option>
<option value="♼">♼</option>
<option value="♽">♽</option>
<option value="♾">♾</option>
<option value="♿">♿</option>
<option value="⚀">⚀</option>
<option value="⚁">⚁</option>
<option value="⚂">⚂</option>
<option value="⚃">⚃</option>
<option value="⚄">⚄</option>
<option value="⚅">⚅</option>
<option value="⚆">⚆</option>
<option value="⚇">⚇</option>
<option value="⚈">⚈</option>
<option value="⚉">⚉</option>
<option value="⚊">⚊</option>
<option value="⚋">⚋</option>
<option value="⚌">⚌</option>
<option value="⚍">⚍</option>
<option value="⚎">⚎</option>
<option value="⚏">⚏</option>
<option value="⚐">⚐</option>
<option value="⚑">⚑</option>
<option value="⚒">⚒</option>
<option value="⚓">⚓</option>
<option value="⚔">⚔</option>
<option value="⚕">⚕</option>
<option value="⚖">⚖</option>
<option value="⚗">⚗</option>
<option value="⚘">⚘</option>
<option value="⚙">⚙</option>
<option value="⚚">⚚</option>
<option value="⚛">⚛</option>
<option value="⚜">⚜</option>
<option value="⚝">⚝</option>
<option value="⚞">⚞</option>
<option value="⚟">⚟</option>
<option value="⚠">⚠</option>
<option value="⚡">⚡</option>
<option value="⚢">⚢</option>
<option value="⚣">⚣</option>
<option value="⚤">⚤</option>
<option value="⚥">⚥</option>
<option value="⚦">⚦</option>
<option value="⚧">⚧</option>
<option value="⚨">⚨</option>
<option value="⚩">⚩</option>
<option value="⚪">⚪</option>
<option value="⚫">⚫</option>
<option value="⚬">⚬</option>
<option value="⚭">⚭</option>
<option value="⚮">⚮</option>
<option value="⚯">⚯</option>
<option value="⚰">⚰</option>
<option value="⚱">⚱</option>
<option value="⚲">⚲</option>
<option value="⚳">⚳</option>
<option value="⚴">⚴</option>
<option value="⚵">⚵</option>
<option value="⚶">⚶</option>
<option value="⚷">⚷</option>
<option value="⚸">⚸</option>
<option value="⚹">⚹</option>
<option value="⚺">⚺</option>
<option value="⚻">⚻</option>
<option value="⚼">⚼</option>
<option value="⚽">⚽</option>
<option value="⚾">⚾</option>
<option value="⚿">⚿</option>
<option value="⛀">⛀</option>
<option value="⛁">⛁</option>
<option value="⛂">⛂</option>
<option value="⛃">⛃</option>
<option value="⛄">⛂</option>
<option value="✁">✁</option>
<option value="✂">✂</option>
<option value="✃">✃</option>
<option value="✄">✄</option>
<option value="✅">✅</option>
<option value="✆">✆</option>
<option value="✇">✇</option>
<option value="✈">✈</option>
<option value="✉">✉</option>
<option value="✊">✊</option>
<option value="✋">✋</option>
<option value="✌">✌</option>
<option value="✍">✍</option>
<option value="✎">✎</option>
<option value="✏">✏</option>
<option value="✐">✐</option>
<option value="✑">✑</option>
<option value="✒">✒</option>
<option value="✓">✓</option>
<option value="✔">✔</option>
<option value="✕">✕</option>
<option value="✖">✖</option>
<option value="✗">✗</option>
<option value="✘">✘</option>
<option value="✙">✙</option>
<option value="✚">✚</option>
<option value="✛">✛</option>
<option value="✜">✜</option>
<option value="✝">✝</option>
<option value="✞">✞</option>
<option value="✟">✟</option>
<option value="✠">✠</option>
<option value="✡">✡</option>
<option value="✢">✢</option>
<option value="✣">✣</option>
<option value="✤">✤</option>
<option value="✥">✥</option>
<option value="✦">✦</option>
<option value="✧">✧</option>
<option value="✨">✨</option>
<option value="✩">✩</option>
<option value="✪">✪</option>
<option value="✫">✫</option>
<option value="✬">✬</option>
<option value="✭">✭</option>
<option value="✮">✮</option>
<option value="✯">✯</option>
<option value="✰">✰</option>
<option value="✱">✱</option>
<option value="✲">✲</option>
<option value="✳">✳</option>
<option value="✴">✴</option>
<option value="✵">✵</option>
<option value="✶">✶</option>
<option value="✷">✷</option>
<option value="✸">✸</option>
<option value="✹">✹</option>
<option value="✺">✺</option>
<option value="✻">✻</option>
<option value="✼">✼</option>
<option value="✽">✽</option>
<option value="✾">✾</option>
<option value="✿">✿</option>
<option value="❀">❀</option>
<option value="❁">❁</option>
<option value="❂">❂</option>
<option value="❃">❃</option>
<option value="❄">❄</option>
<option value="❅">❅</option>
<option value="❆">❆</option>
<option value="❇">❇</option>
<option value="❈">❈</option>
<option value="❉">❉</option>
<option value="❊">❊</option>
<option value="❋">❋</option>
<option value="❌">❌</option>
<option value="❍">❍</option>
<option value="❎">❎</option>
<option value="❏">❏</option>
<option value="❐">❐</option>
<option value="❑">❑</option>
<option value="❒">❒</option>
<option value="❓">❓</option>
<option value="❔">❔</option>
<option value="❕">❕</option>
<option value="❖">❖</option>
<option value="❗">❗</option>
<option value="❘">❘</option>
<option value="❙">❙</option>
<option value="❚">❚</option>
<option value="❛">❛</option>
<option value="❜">❜</option>
<option value="❝">❝</option>
<option value="❞">❞</option>
<option value="❟">❟</option>
<option value="❠">❠</option>
<option value="❡">❡</option>
<option value="❢">❢</option>
<option value="❣">❣</option>
<option value="❤">❤</option>
<option value="❥">❥</option>
<option value="❦">❦</option>
<option value="❧">❧</option>
<option value="❨">❨</option>
<option value="❩">❩</option>
<option value="❪">❪</option>
<option value="❫">❫</option>
<option value="❬">❬</option>
<option value="❭">❭</option>
<option value="❮">❮</option>
<option value="❯">❯</option>
<option value="❰">❰</option>
<option value="❱">❱</option>
<option value="❲">❲</option>
<option value="❳">❳</option>
<option value="❴">❴</option>
<option value="❵">❵</option>
<option value="❶">❶</option>
<option value="❷">❷</option>
<option value="❸">❸</option>
<option value="❹">❹</option>
<option value="❺">❺</option>
<option value="❻">❻</option>
<option value="❼">❼</option>
<option value="❽">❽</option>
<option value="❾">❾</option>
<option value="❿">❿</option>
<option value="➀">➀</option>
<option value="➁">➁</option>
<option value="➂">➂</option>
<option value="➃">➃</option>
<option value="➄">➄</option>
<option value="➅">➅</option>
<option value="➆">➆</option>
<option value="➇">➇</option>
<option value="➈">➈</option>
<option value="➉">➉</option>
<option value="➊">➊</option>
<option value="➋">➋</option>
<option value="➌">➌</option>
<option value="➍">➍</option>
<option value="➎">➎</option>
<option value="➏">➏</option>
<option value="➐">➐</option>
<option value="➑">➑</option>
<option value="➒">➒</option>
<option value="➓">➓</option>
<option value="➔">➔</option>
<option value="➕">➕</option>
<option value="➖">➖</option>
<option value="➗">➗</option>
<option value="➘">➘</option>
<option value="➙">➙</option>
<option value="➚">➚</option>
<option value="➛">➛</option>
<option value="➜">➜</option>
<option value="➝">➝</option>
<option value="➞">➞</option>
<option value="➟">➟</option>
<option value="➠">➠</option>
<option value="➡">➡</option>
<option value="➢">➢</option>
<option value="➣">➣</option>
<option value="➤">➤</option>
<option value="➥">➥</option>
<option value="➦">➦</option>
<option value="➧">➧</option>
<option value="➨">➨</option>
<option value="➩">➩</option>
<option value="➪">➪</option>
<option value="➫">➫</option>
<option value="➬">➬</option>
<option value="➭">➭</option>
<option value="➮">➮</option>
<option value="➯">➯</option>
<option value="➰">➰</option>
<option value="➱">➱</option>
<option value="➲">➲</option>
<option value="➳">➳</option>
<option value="➴">➴</option>
<option value="➵">➵</option>
<option value="➶">➶</option>
<option value="➷">➷</option>
<option value="➸">➸</option>
<option value="➹">➹</option>
<option value="➺">➺</option>
<option value="➻">➻</option>
<option value="➼">➼</option>
<option value="➽">➽</option>
<option value="➾">➾</option>
<option value="➿">➿</option>
<option value="⠂">⠂</option>
<option value="⠃">⠃</option>
<option value="⠄">⠄</option>
<option value="⠅">⠅</option>
<option value="⠆">⠆</option>
<option value="⠇">⠇</option>
<option value="⠈">⠈</option>
<option value="⠉">⠉</option>
<option value="⠊">⠊</option>
<option value="⠋">⠋</option>
<option value="⠌">⠌</option>
<option value="⠍">⠍</option>
<option value="⠎">⠎</option>
<option value="⠏">⠏</option>
<option value="⠐">⠐</option>
<option value="⠑">⠑</option>
<option value="⠒">⠒</option>
<option value="⠓">⠓</option>
<option value="⠔">⠔</option>
<option value="⠕">⠕</option>
<option value="⠖">⠖</option>
<option value="⠗">⠗</option>
<option value="⠘">⠘</option>
<option value="⠙">⠙</option>
<option value="⠚">⠚</option>
<option value="⠛">⠛</option>
<option value="⠜">⠜</option>
<option value="⠝">⠝</option>
<option value="⠞">⠞</option>
<option value="⠟">⠟</option>
<option value="⠠">⠠</option>
<option value="⠡">⠡</option>
<option value="⠢">⠢</option>
<option value="⠣">⠣</option>
<option value="⠤">⠤</option>
<option value="⠥">⠥</option>
<option value="⠦">⠦</option>
<option value="⠧">⠧</option>
<option value="⠨">⠨</option>
<option value="⠩">⠩</option>
<option value="⠪">⠪</option>
<option value="⠫">⠫</option>
<option value="⠬">⠬</option>
<option value="⠭">⠭</option>
<option value="⠮">⠮</option>
<option value="⠯">⠯</option>
<option value="⠰">⠰</option>
<option value="⠱">⠱</option>
<option value="⠲">⠲</option>
<option value="⠳">⠳</option>
<option value="⠴">⠴</option>
<option value="⠵">⠵</option>
<option value="⠶">⠶</option>
<option value="⠷">⠷</option>
<option value="⠸">⠸</option>
<option value="⠹">⠹</option>
<option value="⠺">⠺</option>
<option value="⠻">⠻</option>
<option value="⠼">⠼</option>
<option value="⠽">⠽</option>
<option value="⠾">⠾</option>
<option value="⠿">⠿</option>
<option value="⡀">⡀</option>
<option value="⡁">⡁</option>
<option value="⡂">⡂</option>
<option value="⡃">⡃</option>
<option value="⡄">⡄</option>
<option value="⡅">⡅</option>
<option value="⡆">⡆</option>
<option value="⡇">⡇</option>
<option value="⡈">⡈</option>
<option value="⡉">⡉</option>
<option value="⡊">⡊</option>
<option value="⡋">⡋</option>
<option value="⡌">⡌</option>
<option value="⡍">⡍</option>
<option value="⡎">⡎</option>
<option value="⡏">⡏</option>
<option value="⡐">⡐</option>
<option value="⡑">⡑</option>
<option value="⡒">⡒</option>
<option value="⡓">⡓</option>
<option value="⡔">⡔</option>
<option value="⡕">⡕</option>
<option value="⡖">⡖</option>
<option value="⡗">⡗</option>
<option value="⡘">⡘</option>
<option value="⡙">⡙</option>
<option value="⡚">⡚</option>
<option value="⡛">⡛</option>
<option value="⡜">⡜</option>
<option value="⡝">⡝</option>
<option value="⡞">⡞</option>
<option value="⡟">⡟</option>
<option value="⡠">⡠</option>
<option value="⡡">⡡</option>
<option value="⡢">⡢</option>
<option value="⡣">⡣</option>
<option value="⡤">⡤</option>
<option value="⡥">⡥</option>
<option value="⡦">⡦</option>
<option value="⡧">⡧</option>
<option value="⡨">⡨</option>
<option value="⡩">⡩</option>
<option value="⡪">⡪</option>
<option value="⡫">⡫</option>
<option value="⡬">⡬</option>
<option value="⡭">⡭</option>
<option value="⡮">⡮</option>
<option value="⡯">⡯</option>
<option value="⡰">⡰</option>
<option value="⡱">⡱</option>
<option value="⡲">⡲</option>
<option value="⡳">⡳</option>
<option value="⡴">⡴</option>
<option value="⡵">⡵</option>
<option value="⡶">⡶</option>
<option value="⡷">⡷</option>
<option value="⡸">⡸</option>
<option value="⡹">⡹</option>
<option value="⡺">⡺</option>
<option value="⡻">⡻</option>
<option value="⡼">⡼</option>
<option value="⡽">⡽</option>
<option value="⡾">⡾</option>
<option value="⡿">⡿</option>
<option value="⢀">⢀</option>
<option value="⢁">⢁</option>
<option value="⢂">⢂</option>
<option value="⢃">⢃</option>
<option value="⢄">⢄</option>
<option value="⢅">⢅</option>
<option value="⢆">⢆</option>
<option value="⢇">⢇</option>
<option value="⢈">⢈</option>
<option value="⢉">⢉</option>
<option value="⢊">⢊</option>
<option value="⢋">⢋</option>
<option value="⢌">⢌</option>
<option value="⢍">⢍</option>
<option value="⢎">⢎</option>
<option value="⢏">⢏</option>
<option value="⢐">⢐</option>
<option value="⢑">⢑</option>
<option value="⢒">⢒</option>
<option value="⢓">⢓</option>
<option value="⢔">⢔</option>
<option value="⢕">⢕</option>
<option value="⢖">⢖</option>
<option value="⢗">⢗</option>
<option value="⢘">⢘</option>
<option value="⢙">⢙</option>
<option value="⢚">⢚</option>
<option value="⢛">⢛</option>
<option value="⢜">⢜</option>
<option value="⢝">⢝</option>
<option value="⢞">⢞</option>
<option value="⢟">⢟</option>
<option value="⢠">⢠</option>
<option value="⢡">⢡</option>
<option value="⢢">⢢</option>
<option value="⢣">⢣</option>
<option value="⢤">⢤</option>
<option value="⢥">⢥</option>
<option value="⢦">⢦</option>
<option value="⢧">⢧</option>
<option value="⢨">⢨</option>
<option value="⢩">⢩</option>
<option value="⢪">⢪</option>
<option value="⢫">⢫</option>
<option value="⢬">⢬</option>
<option value="⢭">⢭</option>
<option value="⢮">⢮</option>
<option value="⢯">⢯</option>
<option value="⢰">⢰</option>
<option value="⢱">⢱</option>
<option value="⢲">⢲</option>
<option value="⢳">⢳</option>
<option value="⢴">⢴</option>
<option value="⢵">⢵</option>
<option value="⢶">⢶</option>
<option value="⢷">⢷</option>
<option value="⢸">⢸</option>
<option value="⢹">⢹</option>
<option value="⢺">⢺</option>
<option value="⢻">⢻</option>
<option value="⢼">⢼</option>
<option value="⢽">⢽</option>
<option value="⢾">⢾</option>
<option value="⢿">⢿</option>
<option value="𝄁">𝄁</option>
<option value="𝄂">𝄂</option>
<option value="𝄃">𝄃</option>
<option value="𝄄">𝄄</option>
<option value="𝄅">𝄅</option>
<option value="𝄆">𝄆</option>
<option value="𝄇">𝄇</option>
<option value="𝄈">𝄈</option>
<option value="𝄉">𝄉</option>
<option value="𝄊">𝄊</option>
<option value="𝄋">𝄋</option>
<option value="𝄌">𝄌</option>
<option value="𝄍">𝄍</option>
<option value="𝄎">𝄎</option>
<option value="𝄏">𝄏</option>
<option value="𝄐">𝄐</option>
<option value="𝄑">𝄑</option>
<option value="𝄒">𝄒</option>
<option value="𝄓">𝄓</option>
<option value="𝄔">𝄔</option>
<option value="𝄕">𝄕</option>
<option value="𝄖">𝄖</option>
<option value="𝄗">𝄗</option>
<option value="𝄘">𝄘</option>
<option value="𝄙">𝄙</option>
<option value="𝄚">𝄚</option>
<option value="𝄛">𝄛</option>
<option value="𝄜">𝄜</option>
<option value="𝄝">𝄝</option>
<option value="𝄞">𝄞</option>
<option value="𝄟">𝄟</option>
<option value="𝄠">𝄠</option>
<option value="𝄡">𝄡</option>
<option value="𝄢">𝄢</option>
<option value="𝄣">𝄣</option>
<option value="𝄤">𝄤</option>
<option value="𝄥">𝄥</option>
<option value="𝄦">𝄦</option>
<option value="𝄧">𝄧</option>
<option value="𝄨">𝄨</option>
<option value="𝄩">𝄩</option>
<option value="𝄪">𝄪</option>
<option value="𝄫">𝄫</option>
<option value="𝄬">𝄬</option>
<option value="𝄭">𝄭</option>
<option value="𝄮">𝄮</option>
<option value="𝄯">𝄯</option>
<option value="𝄰">𝄰</option>
<option value="𝄱">𝄱</option>
<option value="𝄲">𝄲</option>
<option value="𝄳">𝄳</option>
<option value="𝄴">𝄴</option>
<option value="𝄵">𝄵</option>
<option value="𝄶">𝄶</option>
<option value="𝄷">𝄷</option>
<option value="𝄸">𝄸</option>
<option value="𝄹">𝄹</option>
<option value="𝄺">𝄺</option>
<option value="𝄻">𝄻</option>
<option value="𝄼">𝄼</option>
<option value="𝄽">𝄽</option>
<option value="𝄾">𝄾</option>
<option value="𝄿">𝄿</option>
<option value="𝅀">𝅀</option>
<option value="𝅁">𝅁</option>
<option value="𝅂">𝅂</option>
<option value="𝅃">𝅃</option>
<option value="𝅄">𝅄</option>
<option value="𝅅">𝅅</option>
<option value="𝅆">𝅆</option>
<option value="𝅇">𝅇</option>
<option value="𝅈">𝅈</option>
<option value="𝅉">𝅉</option>
<option value="𝅊">𝅊</option>
<option value="𝅋">𝅋</option>
<option value="𝅌">𝅌</option>
<option value="𝅍">𝅍</option>
<option value="𝅎">𝅎</option>
<option value="𝅏">𝅏</option>
<option value="𝅐">𝅐</option>
<option value="𝅑">𝅑</option>
<option value="𝅒">𝅒</option>
<option value="𝅓">𝅓</option>
<option value="𝅔">𝅔</option>
<option value="𝅕">𝅕</option>
<option value="𝅖">𝅖</option>
<option value="𝅗">𝅗</option>
<option value="𝅘">𝅘</option>
<option value="𝅙">𝅙</option>
<option value="𝅚">𝅚</option>
<option value="𝅛">𝅛</option>
<option value="𝅜">𝅜</option>
<option value="𝅝">𝅝</option>
<option value="𝅗𝅥">𝅗𝅥</option>
<option value="𝅘𝅥">𝅘𝅥</option>
<option value="𝅘𝅥𝅮">𝅘𝅥𝅮</option>
<option value="𝅘𝅥𝅯">𝅘𝅥𝅯</option>
<option value="𝅘𝅥𝅰">𝅘𝅥𝅰</option>
<option value="𝅘𝅥𝅱">𝅘𝅥𝅱</option>
<option value="𝅘𝅥𝅲">𝅘𝅥𝅲</option>
<option value="𝅥">𝅥</option>
<option value="𝅦">𝅦</option>
<option value="𝅧">𝅧</option>
<option value="𝅨">𝅨</option>
<option value="𝅩">𝅩</option>
<option value="𝅪">𝅪</option>
<option value="𝅫">𝅫</option>
<option value="𝅬">𝅬</option>
<option value="𝆃">𝆃</option>
<option value="𝆄">𝆄</option>
<option value="𝆌">𝆌</option>
<option value="𝆍">𝆍</option>
<option value="𝆎">𝆎</option>
<option value="𝆏">𝆏</option>
<option value="𝆐">𝆐</option>
<option value="𝆑">𝆑</option>
<option value="𝆒">𝆒</option>
<option value="𝆓">𝆓</option>
<option value="𝆔">𝆔</option>
<option value="𝆕">𝆕</option>
<option value="𝆖">𝆖</option>
<option value="𝆗">𝆗</option>
<option value="𝆘">𝆘</option>
<option value="𝆙">𝆙</option>
<option value="𝆚">𝆚</option>
<option value="𝆛">𝆛</option>
<option value="𝆜">𝆜</option>
<option value="𝆝">𝆝</option>
<option value="𝆞">𝆞</option>
<option value="𝆟">𝆟</option>
<option value="𝆠">𝆠</option>
<option value="𝆡">𝆡</option>
<option value="𝆢">𝆢</option>
<option value="𝆣">𝆣</option>
<option value="𝆤">𝆤</option>
<option value="𝆥">𝆥</option>
<option value="𝆦">𝆦</option>
<option value="𝆧">𝆧</option>
<option value="𝆨">𝆨</option>
<option value="𝆩">𝆩</option>
<option value="𝆪">𝆪</option>
<option value="𝆫">𝆫</option>
<option value="𝆬">𝆬</option>
<option value="𝆭">𝆭</option>
<option value="𝆮">𝆮</option>
<option value="𝆯">𝆯</option>
<option value="𝆰">𝆰</option>
<option value="𝆱">𝆱</option>
<option value="𝆲">𝆲</option>
<option value="𝆳">𝆳</option>
<option value="𝆴">𝆴</option>
<option value="𝆵">𝆵</option>
<option value="𝆶">𝆶</option>
<option value="𝆷">𝆷</option>
<option value="𝆸">𝆸</option>
<option value="𝆹">𝆹</option>
<option value="𝆺">𝆺</option>
<option value="𝆹𝅥">𝆹𝅥</option>
<option value="𝆺𝅥">𝆺𝅥</option>
<option value="𝆹𝅥𝅮">𝆹𝅥𝅮</option>
<option value="𝆺𝅥𝅮">𝆺𝅥𝅮</option>
<option value="𝆹𝅥𝅯">𝆹𝅥𝅯</option>
<option value="𝆺𝅥𝅯">𝆺𝅥𝅯</option>
<option value="𝇁">𝇁</option>
<option value="𝇂">𝇂</option>
<option value="𝇃">𝇃</option>
<option value="𝇄">𝇄</option>
<option value="𝇅">𝇅</option>
<option value="𝇆">𝇆</option>
<option value="𝇇">𝇇</option>
<option value="𝇈">𝇈</option>
<option value="𝇉">𝇉</option>
<option value="𝇊">𝇊</option>
<option value="𝇋">𝇋</option>
<option value="𝇌">𝇌</option>
<option value="𝇍">𝇍</option>
<option value="𝇎">𝇎</option>
<option value="𝇏">𝇏</option>
<option value="𝇐">𝇐</option>
<option value="𝇑">𝇑</option>
<option value="𝇒">𝇒</option>
<option value="𝇓">𝇓</option>
<option value="𝇔">𝇔</option>
<option value="𝇕">𝇕</option>
<option value="𝇖">𝇖</option>
<option value="𝇗">𝇗</option>
<option value="𝇘">𝇘</option>
<option value="𝇙">𝇙</option>
<option value="𝇚">𝇚</option>
<option value="𝇛">𝇛</option>
<option value="𝇜">𝇜</option>
<option value="𝇝">𝇝</option>
<option value="𝇞">𝇞</option>
<option value="𝇟">𝇟</option>
<option value="𝇠">𝇠</option>
<option value="𝇡">𝇡</option>
<option value="𝇢">𝇢</option>
<option value="𝇣">𝇣</option>
<option value="𝇤">𝇤</option>
<option value="𝇥">𝇥</option>
<option value="𝇦">𝇦</option>
<option value="𝇧">𝇧</option>
<option value="𝇨">𝇨</option>
<option value="𝇩">𝇩</option>
<option value="𝇪">𝇪</option>
<option value="🀱">🀱</option>
<option value="🀲">🀲</option>
<option value="🀳">🀳</option>
<option value="🀴">🀴</option>
<option value="🀵">🀵</option>
<option value="🀶">🀶</option>
<option value="🀷">🀷</option>
<option value="🀸">🀸</option>
<option value="🀹">🀹</option>
<option value="🀺">🀺</option>
<option value="🀻">🀻</option>
<option value="🀼">🀼</option>
<option value="🀽">🀽</option>
<option value="🀾">🀾</option>
<option value="🀿">🀿</option>
<option value="🁀">🁀</option>
<option value="🁁">🁁</option>
<option value="🁂">🁂</option>
<option value="🁃">🁃</option>
<option value="🁄">🁄</option>
<option value="🁅">🁅</option>
<option value="🁆">🁆</option>
<option value="🁇">🁇</option>
<option value="🁈">🁈</option>
<option value="🁉">🁉</option>
<option value="🁊">🁊</option>
<option value="🁋">🁋</option>
<option value="🁌">🁌</option>
<option value="🁍">🁍</option>
<option value="🁎">🁎</option>
<option value="🁏">🁏</option>
<option value="🁐">🁐</option>
<option value="🁑">🁑</option>
<option value="🁒">🁒</option>
<option value="🁓">🁓</option>
<option value="🁔">🁔</option>
<option value="🁕">🁕</option>
<option value="🁖">🁖</option>
<option value="🁗">🁗</option>
<option value="🁘">🁘</option>
<option value="🁙">🁙</option>
<option value="🁚">🁚</option>
<option value="🁛">🁛</option>
<option value="🁜">🁜</option>
<option value="🁝">🁝</option>
<option value="🁞">🁞</option>
<option value="🁟">🁟</option>
<option value="🁠">🁠</option>
<option value="🁡">🁡</option>
<option value="🁢">🁢</option>
<option value="🁣">🁣</option>
<option value="🁤">🁤</option>
<option value="🁥">🁥</option>
<option value="🁦">🁦</option>
<option value="🁧">🁧</option>
<option value="🁨">🁨</option>
<option value="🁩">🁩</option>
<option value="🁪">🁪</option>
<option value="🁫">🁫</option>
<option value="🁬">🁬</option>
<option value="🁭">🁭</option>
<option value="🁮">🁮</option>
<option value="🁯">🁯</option>
<option value="🁰">🁰</option>
<option value="🁱">🁱</option>
<option value="🁲">🁲</option>
<option value="🁳">🁳</option>
<option value="🁴">🁴</option>
<option value="🁵">🁵</option>
<option value="🁶">🁶</option>
<option value="🁷">🁷</option>
<option value="🁸">🁸</option>
<option value="🁹">🁹</option>
<option value="🁺">🁺</option>
<option value="🁻">🁻</option>
<option value="🁼">🁼</option>
<option value="🁽">🁽</option>
<option value="🁾">🁾</option>
<option value="🁿">🁿</option>
<option value="🂀">🂀</option>
<option value="🂁">🂁</option>
<option value="🂂">🂂</option>
<option value="🂃">🂃</option>
<option value="🂄">🂄</option>
<option value="🂅">🂅</option>
<option value="🂆">🂆</option>
<option value="🂇">🂇</option>
<option value="🂈">🂈</option>
<option value="🂉">🂉</option>
<option value="🂊">🂊</option>
<option value="🂋">🂋</option>
<option value="🂌">🂌</option>
<option value="🂍">🂍</option>
<option value="🂎">🂎</option>
<option value="🂏">🂏</option>
<option value="🂐">🂐</option>
<option value="🂑">🂑</option>
<option value="🂒">🂒</option>
<option value="🂓">🂓</option>

<option value="🂡">🂡</option>
<option value="🂢">🂢</option>
<option value="🂣">🂣</option>
<option value="🂤">🂤</option>
<option value="🂥">🂥</option>
<option value="🂦">🂦</option>
<option value="🂧">🂧</option>
<option value="🂨">🂨</option>
<option value="🂩">🂩</option>
<option value="🂪">🂪</option>
<option value="🂫">🂫</option>
<option value="🂬">🂬</option>
<option value="🂭">🂭</option>
<option value="🂮">🂮</option>
<option value="🂯">🂯</option>
<option value="🂰">🂰</option>
<option value="🂱">🂱</option>
<option value="🂲">🂲</option>
<option value="🂳">🂳</option>
<option value="🂴">🂴</option>
<option value="🂵">🂵</option>
<option value="🂶">🂶</option>
<option value="🂷">🂷</option>
<option value="🂸">🂸</option>
<option value="🂹">🂹</option>
<option value="🂺">🂺</option>
<option value="🂻">🂻</option>
<option value="🂼">🂼</option>
<option value="🂽">🂽</option>
<option value="🂾">🂾</option>
<option value="🂿">🂿</option>
<option value="🃀">🃀</option>
<option value="🃁">🃁</option>
<option value="🃂">🃂</option>
<option value="🃃">🃃</option>
<option value="🃄">🃄</option>
<option value="🃅">🃅</option>
<option value="🃆">🃆</option>
<option value="🃇">🃇</option>
<option value="🃈">🃈</option>
<option value="🃉">🃉</option>
<option value="🃊">🃊</option>
<option value="🃋">🃋</option>
<option value="🃌">🃌</option>
<option value="🃍">🃍</option>
<option value="🃎">🃎</option>
<option value="🃏">🃏</option>
<option value="🃐">🃐</option>
<option value="🃑">🃑</option>
<option value="🃒">🃒</option>
<option value="🃓">🃓</option>
<option value="🃔">🃔</option>
<option value="🃕">🃕</option>
<option value="🃖">🃖</option>
<option value="🃗">🃗</option>
<option value="🃘">🃘</option>
<option value="🃙">🃙</option>
<option value="🃚">🃚</option>
<option value="🃛">🃛</option>
<option value="🃜">🃜</option>
<option value="🃝">🃝</option>
<option value="🃞">🃞</option>
<option value="🃟">🃟</option>
<option value="🃠">🃠</option>
<option value="🃡">🃡</option>
<option value="🃢">🃢</option>
<option value="🃣">🃣</option>
<option value="🃤">🃤</option>
<option value="🃥">🃥</option>
<option value="🃦">🃦</option>
<option value="🃧">🃧</option>
<option value="🃨">🃨</option>
<option value="🃩">🃩</option>
<option value="🃪">🃪</option>
<option value="🃫">🃫</option>
<option value="🃬">🃬</option>
<option value="🃭">🃭</option>
<option value="🃮">🃮</option>
<option value="🃯">🃯</option>
<option value="🃰">🃰</option>
<option value="🃱">🃱</option>
<option value="🃲">🃲</option>
<option value="🃳">🃳</option>
<option value="🃴">🃴</option>
<option value="🃵">🃵</option>
<option value="🚁">🚁</option>
<option value="🚂">🚂</option>
<option value="🚃">🚃</option>
<option value="🚄">🚄</option>
<option value="🚅">🚅</option>
<option value="🚆">🚆</option>
<option value="🚇">🚇</option>
<option value="🚈">🚈</option>
<option value="🚉">🚉</option>
<option value="🚊">🚊</option>
<option value="🚋">🚋</option>
<option value="🚌">🚌</option>
<option value="🚍">🚍</option>
<option value="🚎">🚎</option>
<option value="🚏">🚏</option>
<option value="🚐">🚐</option>
<option value="🚑">🚑</option>
<option value="🚒">🚒</option>
<option value="🚓">🚓</option>
<option value="🚔">🚔</option>
<option value="🚕">🚕</option>
<option value="🚖">🚖</option>
<option value="🚗">🚗</option>
<option value="🚘">🚘</option>
<option value="🚙">🚙</option>
<option value="🚚">🚚</option>
<option value="🚛">🚛</option>
<option value="🚜">🚜</option>
<option value="🚝">🚝</option>
<option value="🚞">🚞</option>
<option value="🚟">🚟</option>
<option value="🚠">🚠</option>
<option value="🚡">🚡</option>
<option value="🚢">🚢</option>
<option value="🚣">🚣</option>
<option value="🚤">🚤</option>
<option value="🚥">🚥</option>
<option value="🚦">🚦</option>
<option value="🚧">🚧</option>
<option value="🚨">🚨</option>
<option value="🚩">🚩</option>
<option value="🚪">🚪</option>
<option value="🚫">🚫</option>
<option value="🚬">🚬</option>
<option value="🚭">🚭</option>
<option value="🚮">🚮</option>
<option value="🚯">🚯</option>
<option value="🚰">🚰</option>
<option value="🚱">🚱</option>
<option value="🚲">🚲</option>
<option value="🚳">🚳</option>
<option value="🚴">🚴</option>
<option value="🚵">🚵</option>
<option value="🚶">🚶</option>
<option value="🚷">🚷</option>
<option value="🚸">🚸</option>
<option value="🚹">🚹</option>
<option value="🚺">🚺</option>
<option value="🚻">🚻</option>
<option value="🚼">🚼</option>
<option value="🚽">🚽</option>
<option value="🚾">🚾</option>
<option value="🚿">🚿</option>
<option value="🛀">🛀</option>
<option value="🛁">🛁</option>
<option value="🛂">🛂</option>
<option value="🛃">🛃</option>
<option value="🛄">🛄</option>
<option value="🛅">🛅</option>
<option value="🛆">🛆</option>
<option value="🛇">🛇</option>
<option value="🛈">🛈</option>
<option value="🛉">🛉</option>
<option value="🛊">🛊</option>
<option value="🛋">🛋</option>
<option value="🛌">🛌</option>
<option value="🛍">🛍</option>
<option value="🛎">🛎</option>
<option value="🛏">🛏</option>
<option value="🛐">🛐</option>
<option value="🛑">🛑</option>
<option value="🛒">🛒</option>
<option value="🛕">🛕</option>
<option value="🛖">🛖</option>
<option value="🛗">🛗</option>
<option value="🛜">🛜</option>
<option value="🛝">🛝</option>
<option value="🛞">🛞</option>
<option value="🛟">🛟</option>
<option value="🌁">🌁</option>
<option value="🌂">🌂</option>
<option value="🌃">🌃</option>
<option value="🌄">🌄</option>
<option value="🌅">🌅</option>
<option value="🌆">🌆</option>
<option value="🌇">🌇</option>
<option value="🌈">🌈</option>
<option value="🌉">🌉</option>
<option value="🌊">🌊</option>
<option value="🌋">🌋</option>
<option value="🌌">🌌</option>
<option value="🌍">🌍</option>
<option value="🌎">🌎</option>
<option value="🌏">🌏</option>
<option value="🌐">🌐</option>
<option value="🌑">🌑</option>
<option value="🌒">🌒</option>
<option value="🌓">🌓</option>
<option value="🌔">🌔</option>
<option value="🌕">🌕</option>
<option value="🌖">🌖</option>
<option value="🌗">🌗</option>
<option value="🌘">🌘</option>
<option value="🌙">🌙</option>
<option value="🌚">🌚</option>
<option value="🌛">🌛</option>
<option value="🌜">🌜</option>
<option value="🌝">🌝</option>
<option value="🌞">🌞</option>
<option value="🌟">🌟</option>
<option value="🌠">🌠</option>
<option value="🌡">🌡</option>
<option value="🌢">🌢</option>
<option value="🌣">🌣</option>
<option value="🌤">🌤</option>
<option value="🌥">🌥</option>
<option value="🌦">🌦</option>
<option value="🌧">🌧</option>
<option value="🌨">🌨</option>
<option value="🌩">🌩</option>
<option value="🌪">🌪</option>
<option value="🌫">🌫</option>
<option value="🌬">🌬</option>
<option value="🌭">🌭</option>
<option value="🌮">🌮</option>
<option value="🌯">🌯</option>
<option value="🌰">🌰</option>
<option value="🌱">🌱</option>
<option value="🌲">🌲</option>
<option value="🌳">🌳</option>
<option value="🌴">🌴</option>
<option value="🌵">🌵</option>
<option value="🌶">🌶</option>
<option value="🌷">🌷</option>
<option value="🌸">🌸</option>
<option value="🌹">🌹</option>
<option value="🌺">🌺</option>
<option value="🌻">🌻</option>
<option value="🌼">🌼</option>
<option value="🌽">🌽</option>
<option value="🌾">🌾</option>
<option value="🌿">🌿</option>
<option value="🍀">🍀</option>
<option value="🍁">🍁</option>
<option value="🍂">🍂</option>
<option value="🍃">🍃</option>
<option value="🍄">🍄</option>
<option value="🍅">🍅</option>
<option value="🍆">🍆</option>
<option value="🍇">🍇</option>
<option value="🍈">🍈</option>
<option value="🍉">🍉</option>
<option value="🍊">🍊</option>
<option value="🍋">🍋</option>
<option value="🍌">🍌</option>
<option value="🍍">🍍</option>
<option value="🍎">🍎</option>
<option value="🍏">🍏</option>
<option value="🍐">🍐</option>
<option value="🍑">🍑</option>
<option value="🍒">🍒</option>
<option value="🍓">🍓</option>
<option value="🍔">🍔</option>
<option value="🍕">🍕</option>
<option value="🍖">🍖</option>
<option value="🍗">🍗</option>
<option value="🍘">🍘</option>
<option value="🍙">🍙</option>
<option value="🍚">🍚</option>
<option value="🍛">🍛</option>
<option value="🍜">🍜</option>
<option value="🍝">🍝</option>
<option value="🍞">🍞</option>
<option value="🍟">🍟</option>
<option value="🍠">🍠</option>
<option value="🍡">🍡</option>
<option value="🍢">🍢</option>
<option value="🍣">🍣</option>
<option value="🍤">🍤</option>
<option value="🍥">🍥</option>
<option value="🍦">🍦</option>
<option value="🍧">🍧</option>
<option value="🍨">🍨</option>
<option value="🍩">🍩</option>
<option value="🍪">🍪</option>
<option value="🍫">🍫</option>
<option value="🍬">🍬</option>
<option value="🍭">🍭</option>
<option value="🍮">🍮</option>
<option value="🍯">🍯</option>
<option value="🍰">🍰</option>
<option value="🍱">🍱</option>
<option value="🍲">🍲</option>
<option value="🍳">🍳</option>
<option value="🍴">🍴</option>
<option value="🍵">🍵</option>
<option value="🍶">🍶</option>
<option value="🍷">🍷</option>
<option value="🍸">🍸</option>
<option value="🍹">🍹</option>
<option value="🍺">🍺</option>
<option value="🍻">🍻</option>
<option value="🍼">🍼</option>
<option value="🍽">🍽</option>
<option value="🍾">🍾</option>
<option value="🍿">🍿</option>
<option value="🎀">🎀</option>
<option value="🎁">🎁</option>
<option value="🎂">🎂</option>
<option value="🎃">🎃</option>
<option value="🎄">🎄</option>
<option value="🎅">🎅</option>
<option value="🎆">🎆</option>
<option value="🎇">🎇</option>
<option value="🎈">🎈</option>
<option value="🎉">🎉</option>
<option value="🎊">🎊</option>
<option value="🎋">🎋</option>
<option value="🎌">🎌</option>
<option value="🎍">🎍</option>
<option value="🎎">🎎</option>
<option value="🎏">🎏</option>
<option value="🎐">🎐</option>
<option value="🎑">🎑</option>
<option value="🎒">🎒</option>
<option value="🎓">🎓</option>
<option value="🎔">🎔</option>
<option value="🎕">🎕</option>
<option value="🎖">🎖</option>
<option value="🎗">🎗</option>
<option value="🎘">🎘</option>
<option value="🎙">🎙</option>
<option value="🎚">🎚</option>
<option value="🎛">🎛</option>
<option value="🎜">🎜</option>
<option value="🎝">🎝</option>
<option value="🎞">🎞</option>
<option value="🎟">🎟</option>
<option value="🎠">🎠</option>
<option value="🎡">🎡</option>
<option value="🎢">🎢</option>
<option value="🎣">🎣</option>
<option value="🎤">🎤</option>
<option value="🎥">🎥</option>
<option value="🎦">🎦</option>
<option value="🎧">🎧</option>
<option value="🎨">🎨</option>
<option value="🎩">🎩</option>
<option value="🎪">🎪</option>
<option value="🎫">🎫</option>
<option value="🎬">🎬</option>
<option value="🎭">🎭</option>
<option value="🎮">🎮</option>
<option value="🎯">🎯</option>
<option value="🎰">🎰</option>
<option value="🎱">🎱</option>
<option value="🎲">🎲</option>
<option value="🎳">🎳</option>
<option value="🎴">🎴</option>
<option value="🎵">🎵</option>
<option value="🎶">🎶</option>
<option value="🎷">🎷</option>
<option value="🎸">🎸</option>
<option value="🎹">🎹</option>
<option value="🎺">🎺</option>
<option value="🎻">🎻</option>
<option value="🎼">🎼</option>
<option value="🎽">🎽</option>
<option value="🎾">🎾</option>
<option value="🎿">🎿</option>
<option value="🥁">🥁</option>
<option value="🏀">🏀</option>
<option value="🏁">🏁</option>
<option value="🏂">🏂</option>
<option value="🏃">🏃</option>
<option value="🏄">🏄</option>
<option value="🏅">🏅</option>
<option value="🏆">🏆</option>
<option value="🏇">🏇</option>
<option value="🏈">🏈</option>
<option value="🏉">🏉</option>
<option value="🏊">🏊</option>
<option value="🏋️">🏋️</option>
<option value="🏌">🏌</option>
<option value="🏍">🏍</option>
<option value="🏎">🏎</option>
<option value="🏏">🏏</option>
<option value="🏐">🏐</option>
<option value="🏑">🏑</option>
<option value="🏒">🏒</option>
<option value="🏓">🏓</option>
<option value="🏔">🏔</option>
<option value="🏕">🏕</option>
<option value="🏖">🏖</option>
<option value="🏗">🏗</option>
<option value="🏘">🏘</option>
<option value="🏙">🏙</option>
<option value="🏚">🏚</option>
<option value="🏛">🏛</option>
<option value="🏜">🏜</option>
<option value="🏝">🏝</option>
<option value="🏞">🏞</option>
<option value="🏟">🏟</option>
<option value="🏠">🏠</option>
<option value="🏡">🏡</option>
<option value="🏢">🏢</option>
<option value="🏣">🏣</option>
<option value="🏤">🏤</option>
<option value="🏥">🏥</option>
<option value="🏦">🏦</option>
<option value="🏧">🏧</option>
<option value="🏨">🏨</option>
<option value="🏩">🏩</option>
<option value="🏪">🏪</option>
<option value="🏫">🏫</option>
<option value="🏬">🏬</option>
<option value="🏭">🏭</option>
<option value="🏮">🏮</option>
<option value="🏯">🏯</option>
<option value="🏰">🏰</option>
<option value="🏱">🏱</option>
<option value="🏲">🏲</option>
<option value="🏳️">🏳️</option>
<option value="🏴">🏴</option>
<option value="🏵">🏵</option>
<option value="🏷">🏷</option>
<option value="🏸">🏸</option>
<option value="🏹">🏹</option>
<option value="🏺">🏺</option>
<option value="🛠">🛠</option>
<option value="🛡">🛡</option>
<option value="🛢">🛢</option>
<option value="🛣">🛣</option>
<option value="🛤">🛤</option>
<option value="🛥">🛥</option>
<option value="🛦">🛦</option>
<option value="🛧">🛧</option>
<option value="🛨">🛨</option>
<option value="🛩">🛩</option>
<option value="🛪">🛪</option>
<option value="🛫">🛫</option>
<option value="🛬">🛬</option>
<option value="🛰">🛰</option>
<option value="🛱">🛱</option>
<option value="🛲">🛲</option>
<option value="🛳">🛳</option>
<option value="🛴">🛴</option>
<option value="🛵">🛵</option>
<option value="🛶">🛶</option>
<option value="🛷">🛷</option>
<option value="🛸">🛸</option>
<option value="🛹">🛹</option>
<option value="🛺">🛺</option>
<option value="🛻">🛻</option>
<option value="🛼">🛼</option>
<option value="🩱">🩱</option>
<option value="🩲">🩲</option>
<option value="🩳">🩳</option>
<option value="🩴">🩴</option>
<option value="🩵">🩵</option>
<option value="🩶">🩶</option>
<option value="🩷">🩷</option>
<option value="🩸">🩸</option>
<option value="🩹">🩹</option>
<option value="🩺">🩺</option>
<option value="🩻">🩻</option>
<option value="🩼">🩼</option>
<option value="🪀">🪀</option>
<option value="🪁">🪁</option>
<option value="🪂">🪂</option>
<option value="🪃">🪃</option>
<option value="🪄">🪄</option>
<option value="🪅">🪅</option>
<option value="🪆">🪆</option>
<option value="🪇">🪇</option>
<option value="🪈">🪈</option>
<option value="🪐">🪐</option>
<option value="🪑">🪑</option>
<option value="🪒">🪒</option>
<option value="🪓">🪓</option>
<option value="🪔">🪔</option>
<option value="🪕">🪕</option>
<option value="🪖">🪖</option>
<option value="🪗">🪗</option>
<option value="🪘">🪘</option>
<option value="🪙">🪙</option>
<option value="🪚">🪚</option>
<option value="🪛">🪛</option>
<option value="🪜">🪜</option>
<option value="🪝">🪝</option>
<option value="🪞">🪞</option>
<option value="🪟">🪟</option>
<option value="🪠">🪠</option>
<option value="🪡">🪡</option>
<option value="🪢">🪢</option>
<option value="🪣">🪣</option>
<option value="🪤">🪤</option>
<option value="🪥">🪥</option>
<option value="🪦">🪦</option>
<option value="🪧">🪧</option>
<option value="🪨">🪨</option>
<option value="🪩">🪩</option>
<option value="🪪">🪪</option>
<option value="🪫">🪫</option>
<option value="🪬">🪬</option>
<option value="🪭">🪭</option>
<option value="🪮">🪮</option>
<option value="🪯">🪯</option>
<option value="🪰">🪰</option>
<option value="🪱">🪱</option>
<option value="🪲">🪲</option>
<option value="🪳">🪳</option>
<option value="🪴">🪴</option>
<option value="🪵">🪵</option>
<option value="🪶">🪶</option>
<option value="🪷">🪷</option>
<option value="🪸">🪸</option>
<option value="🪹">🪹</option>
<option value="🪺">🪺</option>
<option value="🪻">🪻</option>
<option value="🪼">🪼</option>
<option value="🪽">🪽</option>
<option value="🪿">🪿</option>
<option value="🫀">🫀</option>
<option value="🫁">🫁</option>
<option value="🫂">🫂</option>
<option value="🫃">🫃</option>
<option value="🫄">🫄</option>
<option value="🫅">🫅</option>
<option value="🫎">🫎</option>
<option value="🫏">🫏</option>
<option value="🫐">🫐</option>
<option value="🫑">🫑</option>
<option value="🫒">🫒</option>
<option value="🫓">🫓</option>
<option value="🫔">🫔</option>
<option value="🫕">🫕</option>
<option value="🫖">🫖</option>
<option value="🫗">🫗</option>
<option value="🫘">🫘</option>
<option value="🫙">🫙</option>
<option value="🫚">🫚</option>
<option value="🫛">🫛</option>
<option value="🫠">🫠</option>
<option value="🫡">🫡</option>
<option value="🫢">🫢</option>
<option value="🫣">🫣</option>
<option value="🫤">🫤</option>
<option value="🫥">🫥</option>
<option value="🫦">🫦</option>
<option value="🫧">🫧</option>
<option value="🫨">🫨</option>
<option value="🫰">🫰</option>
<option value="🫱">🫱</option>
<option value="🫲">🫲</option>
<option value="🫳">🫳</option>
<option value="🫴">🫴</option>
<option value="🫵">🫵</option>
<option value="🫶">🫶</option>
<option value="🫷">🫷</option>
<option value="🫸">🫸</option>
<option value="🤌">🤌</option>
<option value="🤍">🤍</option>
<option value="🤎">🤎</option>
<option value="🤏">🤏</option>
<option value="🤐">🤐</option>
<option value="🤑">🤑</option>
<option value="🤒">🤒</option>
<option value="🤓">🤓</option>
<option value="🤔">🤔</option>
<option value="🤕">🤕</option>
<option value="🤖">🤖</option>
<option value="🤗">🤗</option>
<option value="🤘">🤘</option>
<option value="🤙">🤙</option>
<option value="🤚">🤚</option>
<option value="🤛">🤛</option>
<option value="🤜">🤜</option>
<option value="🤝">🤝</option>
<option value="🤞">🤞</option>
<option value="🤟">🤟</option>
<option value="🤠">🤠</option>
<option value="🤡">🤡</option>
<option value="🤢">🤢</option>
<option value="🤣">🤣</option>
<option value="🤤">🤤</option>
<option value="🤥">🤥</option>
<option value="🤦">🤦</option>
<option value="🤧">🤧</option>
<option value="🤨">🤨</option>
<option value="🤩">🤩</option>
<option value="🤪">🤪</option>
<option value="🤫">🤫</option>
<option value="🤬">🤬</option>
<option value="🤭">🤭</option>
<option value="🤮">🤮</option>
<option value="🤯">🤯</option>
<option value="🤰">🤰</option>
<option value="🤱">🤱</option>
<option value="🤲">🤲</option>
<option value="🤳">🤳</option>
<option value="🤴">🤴</option>
<option value="🤵">🤵</option>
<option value="🤶">🤶</option>
<option value="🤷">🤷</option>
<option value="🤸">🤸</option>
<option value="🤹">🤹</option>
<option value="🤺">🤺</option>
<option value="🤻">🤻</option>
<option value="🤼">🤼</option>
<option value="🤽">🤽</option>
<option value="🤾">🤾</option>
<option value="🤿">🤿</option>
<option value="🥀">🥀</option>
<option value="🥁">🥁</option>
<option value="🥂">🥂</option>
<option value="🥃">🥃</option>
<option value="🥄">🥄</option>
<option value="🥅">🥅</option>
<option value="🥆">🥆</option>
<option value="🥇">🥇</option>
<option value="🥈">🥈</option>
<option value="🥉">🥉</option>
<option value="🥊">🥊</option>
<option value="🥋">🥋</option>
<option value="🥌">🥌</option>
<option value="🥍">🥍</option>
<option value="🥎">🥎</option>
<option value="🥏">🥏</option>
<option value="🥐">🥐</option>
<option value="🥑">🥑</option>
<option value="🥒">🥒</option>
<option value="🥓">🥓</option>
<option value="🥔">🥔</option>
<option value="🥕">🥕</option>
<option value="🥖">🥖</option>
<option value="🥗">🥗</option>
<option value="🥘">🥘</option>
<option value="🥙">🥙</option>
<option value="🥚">🥚</option>
<option value="🥛">🥛</option>
<option value="🥜">🥜</option>
<option value="🥝">🥝</option>
<option value="🥞">🥞</option>
<option value="🥟">🥟</option>
<option value="🥠">🥠</option>
<option value="🥡">🥡</option>
<option value="🥢">🥢</option>
<option value="🥣">🥣</option>
<option value="🥤">🥤</option>
<option value="🥥">🥥</option>
<option value="🥦">🥦</option>
<option value="🥧">🥧</option>
<option value="🥨">🥨</option>
<option value="🥩">🥩</option>
<option value="🥪">🥪</option>
<option value="🥫">🥫</option>
<option value="🥬">🥬</option>
<option value="🥭">🥭</option>
<option value="🥮">🥮</option>
<option value="🥯">🥯</option>
<option value="🥰">🥰</option>
<option value="🥱">🥱</option>
<option value="🥲">🥲</option>
<option value="🥳">🥳</option>
<option value="🥴">🥴</option>
<option value="🥵">🥵</option>
<option value="🥶">🥶</option>
<option value="🥷">🥷</option>
<option value="🥸">🥸</option>
<option value="🥹">🥹</option>
<option value="🥺">🥺</option>
<option value="🥻">🥻</option>
<option value="🥼">🥼</option>
<option value="🥽">🥽</option>
<option value="🥾">🥾</option>
<option value="🥿">🥿</option>
<option value="🦀">🦀</option>
<option value="🦁">🦁</option>
<option value="🦂">🦂</option>
<option value="🦃">🦃</option>
<option value="🦄">🦄</option>
<option value="🦅">🦅</option>
<option value="🦆">🦆</option>
<option value="🦇">🦇</option>
<option value="🦈">🦈</option>
<option value="🦉">🦉</option>
<option value="🦊">🦊</option>
<option value="🦋">🦋</option>
<option value="🦌">🦌</option>
<option value="🦍">🦍</option>
<option value="🦎">🦎</option>
<option value="🦏">🦏</option>
<option value="🦐">🦐</option>
<option value="🦑">🦑</option>
<option value="🦒">🦒</option>
<option value="🦓">🦓</option>
<option value="🦔">🦔</option>
<option value="🦕">🦕</option>
<option value="🦖">🦖</option>
<option value="🦗">🦗</option>
<option value="🦘">🦘</option>
<option value="🦙">🦙</option>
<option value="🦚">🦚</option>
<option value="🦛">🦛</option>
<option value="🦜">🦜</option>
<option value="🦝">🦝</option>
<option value="🦞">🦞</option>
<option value="🦟">🦟</option>
<option value="🦠">🦠</option>
<option value="🦡">🦡</option>
<option value="🦢">🦢</option>
<option value="🦣">🦣</option>
<option value="🦤">🦤</option>
<option value="🦥">🦥</option>
<option value="🦦">🦦</option>
<option value="🦧">🦧</option>
<option value="🦨">🦨</option>
<option value="🦩">🦩</option>
<option value="🦪">🦪</option>
<option value="🦫">🦫</option>
<option value="🦬">🦬</option>
<option value="🦭">🦭</option>
<option value="🦮">🦮</option>
<option value="🦯">🦯</option>
<option value="🦰">🦰</option>
<option value="🦱">🦱</option>
<option value="🦲">🦲</option>
<option value="🦳">🦳</option>
<option value="🦴">🦴</option>
<option value="🦵">🦵</option>
<option value="🦶">🦶</option>
<option value="🦷">🦷</option>
<option value="🦸">🦸</option>
<option value="🦹">🦹</option>
<option value="🦺">🦺</option>
<option value="🦻">🦻</option>
<option value="🦼">🦼</option>
<option value="🦽">🦽</option>
<option value="🦾">🦾</option>
<option value="🦿">🦿</option>
<option value="🧀">🧀</option>
<option value="🧁">🧁</option>
<option value="🧂">🧂</option>
<option value="🧃">🧃</option>
<option value="🧄">🧄</option>
<option value="🧅">🧅</option>
<option value="🧆">🧆</option>
<option value="🧇">🧇</option>
<option value="🧈">🧈</option>
<option value="🧉">🧉</option>
<option value="🧊">🧊</option>
<option value="🧋">🧋</option>
<option value="🧌">🧌</option>
<option value="🧍">🧍</option>
<option value="🧎">🧎</option>
<option value="🧏">🧏</option>
<option value="🧐">🧐</option>
<option value="🧑">🧑</option>
<option value="🧒">🧒</option>
<option value="🧓">🧓</option>
<option value="🧔">🧔</option>
<option value="🧕">🧕</option>
<option value="🧖">🧖</option>
<option value="🧗">🧗</option>
<option value="🧘">🧘</option>
<option value="🧙">🧙</option>
<option value="🧚">🧚</option>
<option value="🧛">🧛</option>
<option value="🧜">🧜</option>
<option value="🧝">🧝</option>
<option value="🧞">🧞</option>
<option value="🧟">🧟</option>
<option value="🧠">🧠</option>
<option value="🧡">🧡</option>
<option value="🧢">🧢</option>
<option value="🧣">🧣</option>
<option value="🧤">🧤</option>
<option value="🧥">🧥</option>
<option value="🧦">🧦</option>
<option value="🧧">🧧</option>
<option value="🧨">🧨</option>
<option value="🧩">🧩</option>
<option value="🧪">🧪</option>
<option value="🧫">🧫</option>
<option value="🧬">🧬</option>
<option value="🧭">🧭</option>
<option value="🧮">🧮</option>
<option value="🧯">🧯</option>
<option value="🧰">🧰</option>
<option value="🧱">🧱</option>
<option value="🧲">🧲</option>
<option value="🧳">🧳</option>
<option value="🧴">🧴</option>
<option value="🧵">🧵</option>
<option value="🧶">🧶</option>
<option value="🧷">🧷</option>
<option value="🧸">🧸</option>
<option value="🧹">🧹</option>
<option value="🧺">🧺</option>
<option value="🧻">🧻</option>
<option value="🧼">🧼</option>
<option value="🧽">🧽</option>
<option value="🧾">🧾</option>
<option value="🧿">🧿</option>
<option value="-">-</option>
<option value="E">E</option>
<option value="Q">Q</option>
<option value="]">]</option>
<option value="i">i</option>
<option value="u">u</option>
<option value=""></option>
<option value=""></option>
<option value="™">™</option>
<option value="¥">¥</option>
<option value="±">±</option>
<option value="½">½</option>
<option value="É">É</option>
<option value="Õ">Õ</option>
<option value="á">á</option>
<option value="í">í</option>
<option value="ù">ù</option>
<option value="‌">‌</option>
<option value="‘">‘</option>
<option value="․">․</option>
<option value="‰">‰</option>
<option value="‼">‼</option>
<option value="⁈">⁈</option>
<option value="⁔">⁔</option>
<option value="⁠">⁠</option>
<option value="⁬">⁬</option>
<option value="⁰">⁰</option>
<option value="⁼">⁼</option>
<option value="₈">₈</option>
<option value="ₔ">ₔ</option>
<option value="₠">₠</option>
<option value="€">€</option>
<option value="₸">₸</option>
<option value="⃄">⃄</option>
<option value="℀">℀</option>
<option value="ℌ">ℌ</option>
<option value="℘">℘</option>
<option value="ℤ">ℤ</option>
<option value="ℰ">ℰ</option>
<option value="ℼ">ℼ</option>
<option value="ⅈ">ⅈ</option>
<option value="Α">Α</option>
<option value="Ν">Ν</option>
<option value="Ω">Ω</option>
<option value="ε">ε</option>
<option value="ρ">ρ</option>
<option value="⅐">⅐</option>
<option value="⅜">⅜</option>
<option value="Ⅸ">Ⅸ</option>
<option value="ⅴ">ⅴ</option>
<option value="ↀ">ↀ</option>
<option value="↌">↌</option>
<option value="←">←</option>
<option value="↜">↜</option>
<option value="↨">↨</option>
<option value="↴">↴</option>
<option value="⇀">⇀</option>
<option value="⇌">⇌</option>
<option value="⇘">⇘</option>
<option value="⇤">⇤</option>
<option value="⇰">⇰</option>
<option value="⇼">⇼</option>
<option value="⟰">⟰</option>
<option value="⟼">⟼</option>
<option value="⤀">⤀</option>
<option value="⤌">⤌</option>
<option value="⤘">⤘</option>
<option value="⤤">⤤</option>
<option value="⤰">⤰</option>
<option value="⤼">⤼</option>
<option value="⥈">⥈</option>
<option value="⥔">⥔</option>
<option value="⥠">⥠</option>
<option value="⥬">⥬</option>
<option value="⥸">⥸</option>
<option value="🠀">🠀</option>
<option value="🠌">🠌</option>
<option value="🠘">🠘</option>
<option value="🠤">🠤</option>
<option value="🠰">🠰</option>
<option value="🠼">🠼</option>
<option value="🡈">🡈</option>
<option value="🡔">🡔</option>
<option value="🡠">🡠</option>
<option value="🡬">🡬</option>
<option value="🡸">🡸</option>
<option value="🢄">🢄</option>
<option value="🢐">🢐</option>
<option value="🢜">🢜</option>
<option value="🢨">🢨</option>
<option value="🢴">🢴</option>
<option value="🣀">🣀</option>
<option value="🣌">🣌</option>
<option value="🣘">🣘</option>
<option value="🣤">🣤</option>
<option value="🣰">🣰</option>
<option value="🣼">🣼</option>
<option value="∀">∀</option>
<option value="∌">∌</option>
<option value="∘">∘</option>
<option value="∤">∤</option>
<option value="∰">∰</option>
<option value="∼">∼</option>
<option value="≈">≈</option>
<option value="≔">≔</option>
<option value="≠">≠</option>
<option value="≬">≬</option>
<option value="≸">≸</option>
<option value="⊄">⊄</option>
<option value="⊐">⊐</option>
<option value="⊜">⊜</option>
<option value="⊨">⊨</option>
<option value="⊴">⊴</option>
<option value="⋀">⋀</option>
<option value="⋌">⋌</option>
<option value="⋘">⋘</option>
<option value="⋤">⋤</option>
<option value="⋰">⋰</option>
<option value="⋼">⋼</option>
<option value="⟀">⟀</option>
<option value="⟌">⟌</option>
<option value="⟘">⟘</option>
<option value="⟤">⟤</option>
<option value="⦀">⦀</option>
<option value="⦌">⦌</option>
<option value="⦘">⦘</option>
<option value="⦤">⦤</option>
<option value="⦰">⦰</option>
<option value="⦼">⦼</option>
<option value="⧈">⧈</option>
<option value="⧔">⧔</option>
<option value="⧠">⧠</option>
<option value="⧬">⧬</option>
<option value="⧸">⧸</option>
<option value="⨀">⨀</option>
<option value="⨌">⨌</option>
<option value="⨘">⨘</option>
<option value="⨤">⨤</option>
<option value="⨰">⨰</option>
<option value="⨼">⨼</option>
<option value="⩈">⩈</option>
<option value="⩔">⩔</option>
<option value="⩠">⩠</option>
<option value="⩬">⩬</option>
<option value="⩸">⩸</option>
<option value="⪄">⪄</option>
<option value="⪐">⪐</option>
<option value="⪜">⪜</option>
<option value="⪨">⪨</option>
<option value="⪴">⪴</option>
<option value="⫀">⫀</option>
<option value="⫌">⫌</option>
<option value="⫘">⫘</option>
<option value="⫤">⫤</option>
<option value="⫰">⫰</option>
<option value="⫼">⫼</option>
<option value="⌀">⌀</option>
<option value="⌌">⌌</option>
<option value="⌘">⌘</option>
<option value="⌤">⌤</option>
<option value="⌰">⌰</option>
<option value="⌼">⌼</option>
<option value="⍈">⍈</option>
<option value="⍔">⍔</option>
<option value="⍠">⍠</option>
<option value="⍬">⍬</option>
<option value="⍸">⍸</option>
<option value="⎄">⎄</option>
<option value="⎐">⎐</option>
<option value="⎜">⎜</option>
<option value="⎨">⎨</option>
<option value="⎴">⎴</option>
<option value="⏀">⏀</option>
<option value="⏌">⏌</option>
<option value="⏘">⏘</option>
</select>
      <input type="number" class="angleSelect" value="0" style="width:50px"/>°
      <input type="number" class="fontSizeInput" value="40" style="width:60px"/>px
      <input type="color" class="colorInput" value="#000000"/>
      <button class="moveUp">↑</button>
      <button class="moveDown">↓</button>
      <button class="moveLeft">←</button>
      <button class="moveRight">→</button>
      <button class="removeBtn">✖</button>
    `;
    previewObj.symbolsContainer.appendChild(div);

    const moveStep = 2;
    const updateSymbol = () => updatePreview(previewObj);
    const move = (dx, dy) => {
      div.dataset.left = parseFloat(div.dataset.left) + dx;
      div.dataset.top = parseFloat(div.dataset.top) + dy;
      updateSymbol();
    };

    div.querySelectorAll('input, select').forEach(el => el.addEventListener('input', updateSymbol));
    div.querySelector('.moveUp').addEventListener('click', () => move(0, -moveStep));
    div.querySelector('.moveDown').addEventListener('click', () => move(0, moveStep));
    div.querySelector('.moveLeft').addEventListener('click', () => move(-moveStep, 0));
    div.querySelector('.moveRight').addEventListener('click', () => move(moveStep, 0));
    div.querySelector('.removeBtn').addEventListener('click', () => { div.remove(); updateSymbol(); });
  }

  // ---- IMAGES ----
  function addImage(previewObj) {
    const div = document.createElement('div');
    div.className = 'input-group';
    div.dataset.top = 50;
    div.dataset.left = 50;
    div.dataset.scale = 1;
    div.dataset.rotation = 0;
    div.innerHTML = `
      <input type="text" class="imageURLInput" placeholder="Enter image URL" style="width:250px;"/>
      <button class="applyImg">✔️</button>
      <button class="moveUp">↑</button>
      <button class="moveDown">↓</button>
      <button class="moveLeft">←</button>
      <button class="moveRight">→</button>
      <button class="sizeUp">＋</button>
      <button class="sizeDown">－</button>
      <button class="rotateLeft">⟲</button>
      <button class="rotateRight">⟳</button>
      <button class="removeBtn">✖</button>
    `;
    previewObj.imagesContainer.appendChild(div);

    const moveStep = 2, scaleStep = 0.1, rotateStep = 10;
    const updateImage = () => updatePreview(previewObj);
    const move = (dx, dy) => {
      div.dataset.left = parseFloat(div.dataset.left) + dx;
      div.dataset.top = parseFloat(div.dataset.top) + dy;
      updateImage();
    };

    div.querySelector('.applyImg').addEventListener('click', updateImage);
    div.querySelector('.moveUp').addEventListener('click', () => move(0, -moveStep));
    div.querySelector('.moveDown').addEventListener('click', () => move(0, moveStep));
    div.querySelector('.moveLeft').addEventListener('click', () => move(-moveStep, 0));
    div.querySelector('.moveRight').addEventListener('click', () => move(moveStep, 0));
    div.querySelector('.sizeUp').addEventListener('click', () => { div.dataset.scale = parseFloat(div.dataset.scale) + scaleStep; updateImage(); });
    div.querySelector('.sizeDown').addEventListener('click', () => { div.dataset.scale = Math.max(0.1, parseFloat(div.dataset.scale) - scaleStep); updateImage(); });
    div.querySelector('.rotateLeft').addEventListener('click', () => { div.dataset.rotation = parseFloat(div.dataset.rotation) - rotateStep; updateImage(); });
    div.querySelector('.rotateRight').addEventListener('click', () => { div.dataset.rotation = parseFloat(div.dataset.rotation) + rotateStep; updateImage(); });
    div.querySelector('.removeBtn').addEventListener('click', () => { div.remove(); updateImage(); });
  }

  // ---- UPDATE PREVIEW ----
  function updatePreview(previewObj) {
    const { preview, textarea, symbolsContainer, imagesContainer, fontSelect } = previewObj;
    preview.innerHTML = '';

    symbolsContainer.querySelectorAll('.input-group').forEach(div => {
      const sym = div.querySelector('.symbolInput').value.trim() || div.querySelector('.unicodeSelect').value;
      if (!sym) return;
      const span = document.createElement('span');
      span.textContent = sym;
      span.style.fontSize = div.querySelector('.fontSizeInput').value + 'px';
      span.style.color = div.querySelector('.colorInput').value;
      span.style.fontFamily = fontSelect.value;
      span.style.top = div.dataset.top + '%';
      span.style.left = div.dataset.left + '%';
      span.style.transform = `translate(-50%, -50%) rotate(${div.querySelector('.angleSelect').value}deg)`;
      preview.appendChild(span);
    });

    imagesContainer.querySelectorAll('.input-group').forEach(div => {
      const url = div.querySelector('.imageURLInput').value.trim();
      if (!url) return;
      const img = document.createElement('img');
      img.src = url;
      img.style.top = div.dataset.top + '%';
      img.style.left = div.dataset.left + '%';
      img.style.transform = `translate(-50%, -50%) scale(${div.dataset.scale}) rotate(${div.dataset.rotation}deg)`;
      preview.appendChild(img);
    });

    // Sync the HTML in the textarea
    textarea.value = `<div style="position:relative;width:100%;aspect-ratio:5/3;">${preview.innerHTML}</div>`;
  }

  // ---- Animation ----
  function restartPlayback() {
    if (playing) {
      clearInterval(playInterval);
      playAnimation();
    }
  }

  let lastFrameTime = 0;

  function playAnimation() {
    const previews = Array.from(previewContainer.querySelectorAll('.preview'));
    if (previews.length === 0) return;

    playing = true;
    playBtn.textContent = '⏹ Stop';
    currentFrame = 0;

    function renderFrame(timestamp) {
      if (!lastFrameTime) lastFrameTime = timestamp;

      const timeDifference = timestamp - lastFrameTime;

      if (timeDifference >= frameDelay) {
        animationPlayer.innerHTML = '';
        const frame = previews[currentFrame].cloneNode(true);
        frame.classList.add('frameFade');
        frame.style.position = 'absolute';
        frame.style.top = 0;
        frame.style.left = 0;
        animationPlayer.appendChild(frame);

        lastFrameTime = timestamp;
        currentFrame = (currentFrame + 1) % previews.length;
      }

      if (playing) {
        requestAnimationFrame(renderFrame);
      }
    }

    requestAnimationFrame(renderFrame);
  }

  playBtn.addEventListener('click', () => {
    if (!playing) playAnimation();
    else {
      playing = false;
      clearInterval(playInterval);
      playBtn.textContent = '▶ Play';
    }
  });
});
